# Generated by Django 4.2.5 on 2023-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine',
            field=models.CharField(max_length=30),
        ),
    ]
