# Generated by Django 4.2.5 on 2023-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0002_alter_cuisine_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menuType',
        ),
    ]
