# Generated by Django 4.2.5 on 2023-10-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0002_user_remove_publicplace_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graduationapp.user'),
        ),
    ]
