# Generated by Django 4.2.5 on 2023-10-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0003_publicplace_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='ATM',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='airportDropOff',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='bbq',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='carRental',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='cleaningServices',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='currencyExchange',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='dryCleaning',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='faxCopyingServices',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='filteredPool',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='firstAidServices',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='freeParking',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='laundryServices',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='multiBathrooms',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='multiRooms',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='solarHeater',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='towels',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='toy',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='twintyFourHoursFrontDesk',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='wifi',
        ),
        migrations.AddField(
            model_name='amenities',
            name='name',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('farm', 'Farm')], default='', max_length=50),
        ),
    ]
