# Generated by Django 4.2.5 on 2023-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0004_remove_amenities_atm_remove_amenities_airportdropoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
