# Generated by Django 4.2.5 on 2023-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0004_table_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristauser',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
