# Generated by Django 4.2.5 on 2023-10-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0005_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TouristaUser',
        ),
    ]
