# Generated by Django 4.2.4 on 2023-12-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0006_publicplace_cancellationpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='roomId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roomId', to='graduationapp.room'),
        ),
    ]
