# Generated by Django 4.2.5 on 2023-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0006_rename_user_touristauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
