# Generated by Django 4.2.4 on 2023-12-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0007_alter_roombooking_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='roomId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roomBooking', to='graduationapp.room'),
        ),
    ]
