# Generated by Django 4.2.5 on 2023-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0007_publicplace_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristauser',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
