# Generated by Django 4.2.5 on 2023-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0008_alter_touristauser_isowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='governate',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
