# Generated by Django 4.2.4 on 2023-12-23 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0009_alter_roombooking_checkindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
