# Generated by Django 4.2.5 on 2023-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0009_alter_city_name_alter_governate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
