# Generated by Django 4.2.5 on 2023-10-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0010_alter_amenities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='publicPlaceImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
