# Generated by Django 4.2.5 on 2023-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0011_publicplace_publicplaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='publicPlaceImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
