# Generated by Django 4.2.4 on 2024-01-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0011_farm_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmbooking',
            name='farmId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graduationapp.farm'),
        ),
    ]
