# Generated by Django 4.2.4 on 2024-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0012_alter_farmbooking_farmid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='cityName',
        ),
        migrations.RenameField(
            model_name='governate',
            old_name='name',
            new_name='governateName',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='streetName',
        ),
    ]
