# Generated by Django 4.2.5 on 2023-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0012_alter_publicplace_publicplaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
