# Generated by Django 4.2.5 on 2023-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0013_alter_images_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicplace',
            name='publicPlaceImage',
        ),
    ]
