# Generated by Django 4.2.4 on 2024-02-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0013_rename_name_city_cityname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='price',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='tableId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tableId', to='graduationapp.table'),
        ),
    ]
