# Generated by Django 4.2.4 on 2024-02-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduationapp', '0014_remove_tablebooking_price_tablebooking_tableid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmbooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='price',
        ),
    ]
